import fs from 'node:fs/promises';
import path from 'node:path';

export const README_AUTO_UPDATE_INTERVAL = 86400;
export const README_INSTALL_ROOT = 'Resource/Install/QuantumultX';
export const README_CATEGORY_ORDER = Object.freeze(['BoxJs', 'Module', 'Adblock', 'Rule']);

const RAW_BASE = 'https://raw.githubusercontent.com/JuemingDC/WayX/main';
const BLOB_BASE = 'https://github.com/JuemingDC/WayX/blob/main';
const QX_UNIVERSAL_BASE = 'https://quantumult.app/x/open-app/add-resource?remote-resource=';
const SURGE_WEB_INSTALL_BASE = 'https://surge.app/install-module?url=';
const BOXJS_SUBSCRIBE_BASE = 'https://boxjs.com/#/sub/add/';
const STALE_WAYX_SCRIPT_RAW = 'https://raw.githubusercontent.com/JuemingDC/WayX/main/script/';

function normalizePlatformPart(value) {
  return String(value ?? '').toLowerCase().replace(/[\s_-]+/g, '');
}

function encodeRepoPath(rel) {
  return String(rel).split('/').map(encodeURIComponent).join('/');
}

export function rawRepoUrl(rel) {
  return `${RAW_BASE}/${encodeRepoPath(rel)}`;
}

export function blobRepoUrl(rel) {
  return `${BLOB_BASE}/${encodeRepoPath(rel)}`;
}

export function extractResourceName(text, fallback='') {
  const source = String(text ?? '');
  const qx = source.match(/^#\s*name\s*:\s*(.+?)\s*$/im);
  if (qx?.[1]) return qx[1].trim();
  const surge = source.match(/^#!name\s*=\s*(.+?)\s*$/im);
  if (surge?.[1]) return surge[1].trim();
  try {
    const json = JSON.parse(source);
    if (typeof json?.name === 'string' && json.name.trim()) return json.name.trim();
  } catch {}
  return String(fallback ?? '').trim();
}

export function qxAddResourceUrl(payload) {
  return QX_UNIVERSAL_BASE + encodeURIComponent(JSON.stringify(payload));
}

function safeTag(value) {
  return String(value ?? '').replace(/,/g, '，').trim();
}

function qxRemoteDescriptor(url, tag) {
  return `${url}, tag=${safeTag(tag)}, update-interval=${README_AUTO_UPDATE_INTERVAL}, enabled=true`;
}

export function surgeModuleInstallUrl(rel) {
  return SURGE_WEB_INSTALL_BASE + encodeURIComponent(rawRepoUrl(rel));
}

export function boxJsSubscribeUrl(rel) {
  return BOXJS_SUBSCRIBE_BASE + encodeURIComponent(rawRepoUrl(rel));
}

export function splitQxSnippet(text) {
  const sections = {filter_local: [], rewrite_local: [], mitm: []};
  let current = null;
  let sawMarker = false;
  for (const line of String(text ?? '').replace(/\r\n?/g, '\n').split('\n')) {
    const marker = line.match(/^\s*#\s*\[(filter_local|rewrite_local|mitm)\]\s*$/i);
    if (marker) {
      current = marker[1].toLowerCase();
      sawMarker = true;
      continue;
    }
    if (current) sections[current].push(line);
  }
  if (!sawMarker) throw new Error('Quantumult X snippet is missing commented section markers');

  const clean = lines => lines.join('\n').replace(/^\s*\n+/, '').replace(/\n+\s*$/, '').trimEnd();
  const filter = clean(sections.filter_local);
  const rewriteParts = [clean(sections.rewrite_local), clean(sections.mitm)].filter(Boolean);
  return {filter, rewrite: rewriteParts.join('\n\n')};
}

function generatedInstallerText({sourceRel, name, kind, body}) {
  return [
    '# Generated by WayX README index. Do not edit manually.',
    `# Name: ${name}`,
    `# Source: ${rawRepoUrl(sourceRel)}`,
    `# Kind: ${kind}`,
    `# Update interval: ${README_AUTO_UPDATE_INTERVAL} seconds (24 hours)`,
    '',
    String(body).trimEnd(),
    '',
  ].join('\n');
}

async function walkFiles(root, rel) {
  const abs = path.join(root, rel);
  let entries;
  try { entries = await fs.readdir(abs, {withFileTypes: true}); }
  catch (error) {
    if (error?.code === 'ENOENT') return [];
    throw error;
  }
  const out = [];
  for (const ent of entries.sort((a,b)=>a.name.localeCompare(b.name,'en'))) {
    if (ent.name.startsWith('.')) continue;
    const child = path.posix.join(rel.replaceAll(path.sep, '/'), ent.name);
    if (ent.isDirectory()) out.push(...await walkFiles(root, child));
    else if (ent.isFile()) out.push(child);
  }
  return out;
}

function detectPlatform(rel) {
  for (const part of String(rel).split('/')) {
    const key = normalizePlatformPart(part);
    if (key === 'quantumultx' || key === 'quanx') return 'qx';
    if (key === 'surge') return 'surge';
  }
  return null;
}

function stemOf(rel) {
  const base = path.posix.basename(rel);
  return base.replace(/\.[^.]+$/, '');
}

function rowKey(category, rel) {
  const parts = rel.split('/');
  if (category === 'Module') return parts[1] || stemOf(rel);
  return stemOf(rel);
}

async function scanCategory(root, category) {
  const dir = category === 'BoxJs' ? 'Boxjs' : category;
  const files = await walkFiles(root, dir);
  const rows = new Map();
  for (const rel of files) {
    const ext = path.posix.extname(rel).toLowerCase();
    if (category === 'BoxJs' && ext !== '.json') continue;
    if (category === 'Module' && !['.snippet', '.sgmodule'].includes(ext)) continue;
    if (category === 'Adblock' && !['.snippet', '.sgmodule'].includes(ext)) continue;
    if (category === 'Rule' && !['.list', '.snippet', '.sgmodule'].includes(ext)) continue;
    const platform = detectPlatform(rel);
    if (!platform && category !== 'BoxJs') continue;
    const text = await fs.readFile(path.join(root, rel), 'utf8');
    if (text.includes(STALE_WAYX_SCRIPT_RAW)) {
      throw new Error(`stale lowercase WayX Script raw URL in indexed resource: ${rel}`);
    }
    const fallback = stemOf(rel);
    const name = extractResourceName(text, fallback);
    const key = rowKey(category, rel);
    const row = rows.get(key) ?? {key, qx:null, surge:null, boxjs:null};
    const item = {rel, name, text, ext};
    if (category === 'BoxJs') {
      if (platform === 'surge') row.surge = item;
      else row.qx = item;
    } else {
      if (platform === 'qx') row.qx = item;
      if (platform === 'surge') row.surge = item;
    }
    rows.set(key, row);
  }
  return [...rows.values()].sort((a,b)=>a.key.localeCompare(b.key,'en'));
}

function qxInstallerForSnippet(category, item, desiredFiles) {
  const {filter, rewrite} = splitQxSnippet(item.text);
  if (!filter && !rewrite) throw new Error(`empty Quantumult X snippet: ${item.rel}`);
  const base = stemOf(item.rel);
  const payload = {};
  if (filter) {
    const rel = `${README_INSTALL_ROOT}/${category}/${base}.filter.list`;
    desiredFiles.set(rel, generatedInstallerText({sourceRel:item.rel,name:item.name,kind:'filter_remote',body:filter}));
    payload.filter_remote = [qxRemoteDescriptor(rawRepoUrl(rel), `${item.name} · Filter`)];
  }
  if (rewrite) {
    const rel = `${README_INSTALL_ROOT}/${category}/${base}.rewrite.snippet`;
    desiredFiles.set(rel, generatedInstallerText({sourceRel:item.rel,name:item.name,kind:'rewrite_remote',body:rewrite}));
    payload.rewrite_remote = [qxRemoteDescriptor(rawRepoUrl(rel), `${item.name} · Rewrite`)];
  }
  return qxAddResourceUrl(payload);
}

function qxInstallerForRule(item) {
  const payload = {filter_remote:[qxRemoteDescriptor(rawRepoUrl(item.rel), item.name)]};
  return qxAddResourceUrl(payload);
}

function markdownLink(label, url) {
  return `[${label}](${url})`;
}

function resourceNameCell(row) {
  const item = row.qx ?? row.surge;
  return item ? `**[${item.name}](${blobRepoUrl(item.rel)})**` : `**${row.key}**`;
}

function rowInstallCells(category, row, desiredFiles) {
  let qx = '—';
  let surge = '—';
  if (category === 'BoxJs' && row.qx) {
    qx = markdownLink('一键添加', boxJsSubscribeUrl(row.qx.rel));
  } else if (row.qx && (category === 'Module' || category === 'Adblock')) {
    qx = markdownLink('一键导入', qxInstallerForSnippet(category, row.qx, desiredFiles));
  } else if (row.qx && category === 'Rule') {
    qx = markdownLink('一键导入', qxInstallerForRule(row.qx));
  }

  if (row.surge) {
    if (row.surge.ext === '.sgmodule') surge = markdownLink('一键安装', surgeModuleInstallUrl(row.surge.rel));
    else surge = markdownLink('查看规则', rawRepoUrl(row.surge.rel));
  }
  return {qx, surge};
}

function renderTable(category, rows, desiredFiles) {
  const lines = [
    `## ${category}`,
    '',
    '| Name | Quantumult X | Surge |',
    '| :--- | :---: | :---: |',
  ];
  for (const row of rows) {
    const cells = rowInstallCells(category, row, desiredFiles);
    lines.push(`| ${resourceNameCell(row)} | ${cells.qx} | ${cells.surge} |`);
  }
  if (!rows.length) lines.push('| — | — | — |');
  return lines.join('\n');
}

export async function buildReadmePlan(root=process.cwd()) {
  const desiredFiles = new Map();
  const sections = [];
  for (const category of README_CATEGORY_ORDER) {
    const rows = await scanCategory(root, category);
    sections.push(renderTable(category, rows, desiredFiles));
  }

  const readme = [
    '<div align="center">',
    '',
    '# WayX',
    '',
    '**Quantumult X · Surge**',
    '',
    '规则、模块及去广告资源转换与维护',
    '',
    '[BoxJs](#boxjs) · [Module](#module) · [Adblock](#adblock) · [Rule](#rule)',
    '',
    '</div>',
    '',
    '---',
    '',
    sections.join('\n\n---\n\n'),
    '',
    '---',
    '',
    '<div align="center">',
    '',
    'WayX · Maintained by **chance**',
    '',
    '</div>',
    '',
  ].join('\n');
  desiredFiles.set('README.md', readme);
  return desiredFiles;
}

async function currentGeneratedInstallerFiles(root) {
  return (await walkFiles(root, README_INSTALL_ROOT)).filter(rel=>!rel.endsWith('/.gitkeep'));
}

export async function readmePlanDiff(root=process.cwd(), plan=null) {
  const desired = plan ?? await buildReadmePlan(root);
  const changed = [];
  for (const [rel,content] of desired) {
    let current = null;
    try { current = await fs.readFile(path.join(root,rel),'utf8'); } catch (error) {
      if (error?.code !== 'ENOENT') throw error;
    }
    if (current !== content) changed.push(rel);
  }
  const desiredInstall = new Set([...desired.keys()].filter(rel=>rel.startsWith(README_INSTALL_ROOT+'/')));
  for (const rel of await currentGeneratedInstallerFiles(root)) {
    if (!desiredInstall.has(rel)) changed.push('delete:'+rel);
  }
  return changed.sort();
}

export async function writeReadmePlan(root=process.cwd(), plan=null) {
  const desired = plan ?? await buildReadmePlan(root);
  const desiredInstall = new Set([...desired.keys()].filter(rel=>rel.startsWith(README_INSTALL_ROOT+'/')));
  for (const [rel,content] of desired) {
    const abs = path.join(root,rel);
    await fs.mkdir(path.dirname(abs),{recursive:true});
    await fs.writeFile(abs,content);
  }
  for (const rel of await currentGeneratedInstallerFiles(root)) {
    if (desiredInstall.has(rel)) continue;
    await fs.unlink(path.join(root,rel));
  }
  return desired;
}
